import { ChildData } from './type';

export const seedChildren: ChildData[] = [
  {
    id: 'C001',
    prefix: 'เด็กชาย',
    fullName: 'สมชาย ใจดี',
    birthDate: '15 มกราคม 2561',
    personalId: '1-2345-67890-12-3',
    religion: 'พุทธ',
    bloodType: 'O',
    address: {
      houseNumber: '123/45',
      moo: '5',
      road: 'สุขุมวิท',
      alley: 'สุขุมวิท 101/1',
      subDistrict: 'บางนา',
      district: 'บางนา',
      province: 'กรุงเทพมหานคร',
      postalCode: '10260',
      phone: '02-123-4567',
      permanent: {
        houseNumber: '88/9',
        moo: '7',
        road: 'พหลโยธิน',
        alley: 'พหลโยธิน 34',
        subDistrict: 'จตุจักร',
        district: 'จตุจักร',
        province: 'กรุงเทพมหานคร',
        postalCode: '10900',
      },
    },
    father: {
      fullName: 'นายสมบัติ ใจดี',
      age: '35 ปี',
      job: 'วิศวกร',
      phone: '081-234-5678',
      income: '600,000 บาท',
    },
    mother: {
      fullName: 'นางสมศรี ใจดี',
      age: '32 ปี',
      job: 'ครู',
      phone: '089-876-5432',
      income: '480,000 บาท',
    },
    guardian: {
      fullName: '-',
      age: '-',
      job: '-',
      phone: '-',
      income: '-',
      relation: '-',
    },
    growthHistory: [
      {
        date: '15/01/2566',
        age: '5 ปี 0 เดือน',
        weight: 18.5,
        height: 110.0,
        bmi: 15.3,
        status: 'ปกติ',
      },
      {
        date: '15/10/2565',
        age: '4 ปี 9 เดือน',
        weight: 17.8,
        height: 108.5,
        bmi: 15.1,
        status: 'ปกติ',
      },
      {
        date: '15/07/2565',
        age: '4 ปี 6 เดือน',
        weight: 17.2,
        height: 107.0,
        bmi: 15.0,
        status: 'ปกติ',
      },
      {
        date: '15/04/2565',
        age: '4 ปี 3 เดือน',
        weight: 16.5,
        height: 105.5,
        bmi: 14.8,
        status: 'ปกติ',
      },
      {
        date: '15/01/2565',
        age: '4 ปี 0 เดือน',
        weight: 16.0,
        height: 104.0,
        bmi: 14.8,
        status: 'ปกติ',
      },
    ],
    growthChart: [
      { age: '1 ปี', weight: 10, height: 80 },
      { age: '2 ปี', weight: 12.5, height: 88 },
      { age: '3 ปี', weight: 14.8, height: 96 },
      { age: '4 ปี', weight: 16.2, height: 104 },
      { age: '5 ปี', weight: 18.5, height: 110 },
      { age: '6 ปี', weight: 20.7, height: 116 },
      { age: '7 ปี', weight: 22.3, height: 120 },
    ],
  },
];
